//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_cuoc
    {
        public long id { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime date_go { get; set; }
        public System.DateTime date_back { get; set; }
    
        public virtual taxi taxis { get; set; }
    }
}
