//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class checker : entity
    {
        public checker()
        {
            this.taxis = new HashSet<taxi>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual user_role user_role { get; set; }
        public virtual leader leader { get; set; }
        public virtual ICollection<taxi> taxis { get; set; }
    }
}
