//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class checker : entity
    {
        public checker()
        {
            this.principal = new HashSet<leader>();
            this.taxi_relation_checker = new HashSet<taxi_relation_checker>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual user_role user_role { get; set; }
        public virtual ICollection<leader> principal { get; set; }
        public virtual ICollection<taxi_relation_checker> taxi_relation_checker { get; set; }
    }
}
