//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver_percentange
    {
        public int id { get; set; }
        public string percent { get; set; }
    
        public virtual taxi_type taxi_type { get; set; }
        public virtual price_range price { get; set; }
    }
}
