//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityDiagramContainer : DbContext
    {
        public EntityDiagramContainer()
            : base("name=EntityDiagramContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<entity> enties { get; set; }
        public virtual DbSet<taxi> taxis { get; set; }
        public virtual DbSet<taxi_type> taxi_types { get; set; }
        public virtual DbSet<price_range> price_ranges { get; set; }
        public virtual DbSet<driver_percentange> driver_percentanges { get; set; }
        public virtual DbSet<sumary_number> sumary_numbers { get; set; }
        public virtual DbSet<day_income> day_incomes { get; set; }
        public virtual DbSet<province_income> province_incomes { get; set; }
        public virtual DbSet<subtraction_income> subtraction_incomes { get; set; }
        public virtual DbSet<repair_cost> repair_costs { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<trip_check> trip_checks { get; set; }
        public virtual DbSet<collection> collections { get; set; }
        public virtual DbSet<reason_no_income> reason_no_incomes { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
    }
}
