//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityDiagramContainer : DbContext
    {
        public EntityDiagramContainer()
            : base("name=EntityDiagramContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<entity> entities { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<taxi> taxis1 { get; set; }
        public virtual DbSet<taxi_type> taxi_type { get; set; }
        public virtual DbSet<price_range> price_range { get; set; }
        public virtual DbSet<driver_percentange> driver_percentange { get; set; }
        public virtual DbSet<sumary_number> sumary_number { get; set; }
        public virtual DbSet<day_income> day_income { get; set; }
        public virtual DbSet<province_income> province_income { get; set; }
        public virtual DbSet<subtraction_income> subtraction_income { get; set; }
        public virtual DbSet<repair_cost> repair_cost { get; set; }
        public virtual DbSet<leader> leaders { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<check_cuoc> check_cuoc { get; set; }
        public virtual DbSet<Collection> Collections { get; set; }
    }
}
