//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class entity
    {
        public entity()
        {
            this.checkers = new HashSet<entity>();
            this.taxis = new HashSet<taxi>();
        }
    
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public bool gender { get; set; }
        public string email { get; set; }
        public string businessphone { get; set; }
        public Nullable<System.DateTime> date_join { get; set; }
    
        public virtual user_role user_role { get; set; }
        public virtual ICollection<entity> checkers { get; set; }
        public virtual entity leader { get; set; }
        public virtual group groups { get; set; }
        public virtual ICollection<taxi> taxis { get; set; }
    }
}
