//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_relation_leader
    {
        public int id { get; set; }
        public string date_start { get; set; }
        public string date_end { get; set; }
    
        public virtual group group { get; set; }
        public virtual leader leader { get; set; }
    }
}
