//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class leader
    {
        public leader()
        {
            this.checkers = new HashSet<checker>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual user_role user_roles { get; set; }
        public virtual ICollection<checker> checkers { get; set; }
        public virtual group group { get; set; }
    }
}
