//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class price_range
    {
        public price_range()
        {
            this.driver_percentange = new HashSet<driver_percentange>();
        }
    
        public int id { get; set; }
        public string start { get; set; }
        public string end { get; set; }
    
        public virtual ICollection<driver_percentange> driver_percentange { get; set; }
    }
}
