//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvineIncome
    {
        public long id { get; set; }
        public System.DateTime created { get; set; }
        public int tripIncome { get; set; }
        public int overIncome { get; set; }
        public int priceIncome { get; set; }
    
        public virtual Taxi Taxi { get; set; }
    }
}
