//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class subtraction_income
    {
        public long id { get; set; }
        public int taximet { get; set; }
        public string cuopco { get; set; }
        public string another { get; set; }
        public string thuxe { get; set; }
    
        public virtual taxi taxi { get; set; }
    }
}
