//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class sumary_number
    {
        public long id { get; set; }
        public System.DateTime created { get; set; }
        public int total { get; set; }
        public int km { get; set; }
        public string cuoc { get; set; }
    
        public virtual taxi taxi { get; set; }
    }
}
