//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxi
    {
        public taxi()
        {
            this.driver = new HashSet<driver>();
            this.sumary_number = new HashSet<sumary_number>();
            this.day_income = new HashSet<day_income>();
            this.income_provine = new HashSet<province_income>();
            this.subtraction_income = new HashSet<subtraction_income>();
            this.repair_cost = new HashSet<repair_cost>();
            this.check_cuoc = new HashSet<check_cuoc>();
        }
    
        public int id { get; set; }
        public string number_car { get; set; }
        public Nullable<System.DateTime> date_join { get; set; }
        public string model { get; set; }
    
        public virtual taxi_type taxi_type { get; set; }
        public virtual ICollection<driver> driver { get; set; }
        public virtual ICollection<sumary_number> sumary_number { get; set; }
        public virtual ICollection<day_income> day_income { get; set; }
        public virtual ICollection<province_income> income_provine { get; set; }
        public virtual ICollection<subtraction_income> subtraction_income { get; set; }
        public virtual ICollection<repair_cost> repair_cost { get; set; }
        public virtual ICollection<check_cuoc> check_cuoc { get; set; }
        public virtual checker checker { get; set; }
    }
}
