//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxiType
    {
        public TaxiType()
        {
            this.Taxis = new HashSet<Taxi>();
            this.DriverPercentanges = new HashSet<DriverPercentange>();
        }
    
        public short id { get; set; }
        public string description { get; set; }
        public string symbol { get; set; }
    
        public virtual ICollection<Taxi> Taxis { get; set; }
        public virtual ICollection<DriverPercentange> DriverPercentanges { get; set; }
    }
}
