//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role
    {
        public user_role()
        {
            this.checkers = new HashSet<checker>();
            this.leaders = new HashSet<leader>();
        }
    
        public short id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<checker> checkers { get; set; }
        public virtual ICollection<leader> leaders { get; set; }
    }
}
