//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role
    {
        public short id { get; set; }
        public string description { get; set; }
        public string permission { get; set; }
    
        public virtual checker checker { get; set; }
        public virtual leader leader { get; set; }
        public virtual moderator moderator { get; set; }
        public virtual administrator administrator { get; set; }
    }
}
