//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun.EntityClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Groups = new HashSet<Group>();
        }
    
        public int id { get; set; }
        public System.DateTime created { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
    }
}
