//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun.EntityClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayIncome
    {
        public long id { get; set; }
        public System.DateTime created { get; set; }
        public int moneySum { get; set; }
        public int driverIncome { get; set; }
        public int companyIncome { get; set; }
        public int rateIncome { get; set; }
    
        public virtual Taxi Taxi { get; set; }
    }
}
