//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun.EntityClass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityDiagramContainer : DbContext
    {
        public EntityDiagramContainer()
            : base("name=EntityDiagramContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<Taxi> Taxis { get; set; }
        public virtual DbSet<TaxiType> TaxiTypes { get; set; }
        public virtual DbSet<PriceRange> PriceRanges { get; set; }
        public virtual DbSet<DriverPercentange> DriverPercentanges { get; set; }
        public virtual DbSet<SummaryNumber> SummaryNumbers { get; set; }
        public virtual DbSet<DayIncome> DayIncomes { get; set; }
        public virtual DbSet<ProvineIncome> ProvineIncomes { get; set; }
        public virtual DbSet<SubtractionIncome> SubtractionIncomes { get; set; }
        public virtual DbSet<RepairCost> RepairCosts { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<TripCheck> TripChecks { get; set; }
        public virtual DbSet<Collection> Collections { get; set; }
        public virtual DbSet<ReasonNoIncome> ReasonNoIncomes { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
    }
}
