//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun.EntityClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Collections = new HashSet<Collection>();
            this.Entities = new HashSet<Entity>();
            this.Taxis = new HashSet<Taxi>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<Collection> Collections { get; set; }
        public virtual ICollection<Entity> Entities { get; set; }
        public virtual ICollection<Taxi> Taxis { get; set; }
    }
}
