//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasun.EntityClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceRange
    {
        public PriceRange()
        {
            this.DriverPercentanges = new HashSet<DriverPercentange>();
        }
    
        public short id { get; set; }
        public int start { get; set; }
        public int end { get; set; }
    
        public virtual ICollection<DriverPercentange> DriverPercentanges { get; set; }
    }
}
